hw3: driver_template.o algorithm_template.o
	gcc driver_template.o algorithm_template.o -o hw3
algorithm_template.o: algorithm_template.c header.h
	gcc -c algorithm_template.c
driver_template.o: driver_template.c header.h
	gcc -c driver_template.c
